# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    container_name: server
    command: npm run start:dev
    depends_on:
      - model
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.compose
    ports:
      - 3000:3000
      - 5002:5002
  model:
    container_name: model
    image: ollama/ollama:0.6.2
    ports:
      - 11434:11434
    post_start:
      - command: ollama pull llama3.2
