name: Build and deploy images

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      IMAGE_TAG:
        required: true
        type: string

env:
  REGISTRY: samanthamorris684
  FRONTEND_IMAGE_NAME: catbot-frontend
  BACKEND_IMAGE_NAME: catbot-backend
  USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "demonstrationorg/default"
          install: true

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
        
        
    
    

