name: Build and deploy image

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      IMAGE_TAG:
        required: true
        type: string

env:
  IMAGE_NAME: samanthamorris684/catbot
  USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - uses: actions/checkout@v4
      - name: Build and push the Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

        
        
    
    

