name: Build and deploy image

on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      IMAGE_TAG:
        required: true
        type: string

env:
  IMAGE_NAME: samanthamorris684/catbot
  # Change this from latest
  COMPARE_TAG: latest
  USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      
      - name: Build and push the Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ inputs.IMAGE_TAG }} .
          docker push $IMAGE_NAME:${{ inputs.IMAGE_TAG }}

      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: compare
          image: $IMAGE_NAME:${{ inputs.IMAGE_TAG }}
          to: ${{ env.IMAGE_NAME }}:${{ env.COMPARE_TAG }}
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }} # to be able to write the comment
        
        
    
    

