name: Build and deploy image

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string

env:
  IMAGE_NAME: samanthamorris684/catbot

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4
      - name: Build and push the Docker image
        run: |
          - docker build -t $IMAGE_NAME:$TAG .
          - docker push $IMAGE_NAME:$TAG

        
        
    
    

