name: Deployment workflow

on:
  workflow_call:
    secrets:
      GH_ACTIONS_ROLE:
        required: true
    inputs:
      IMAGE_TAG:
        required: true
        type: string

env:
  REGISTRY: samanthamorris684
  FRONTEND_IMAGE_NAME: catbot-frontend
  BACKEND_IMAGE_NAME: catbot-backend
  EKS_CLUSTER_NAME: catbot-cluster
  NAMESPACE: cat-chatbot
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-eks:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
          kubectl set image deployment/frontend frontend=${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/frontend -n ${{ env.NAMESPACE }}
          kubectl set image deployment/backend backend=${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/backend -n ${{ env.NAMESPACE }}
