name: Feature branch workflow

on:
  push:
    branches-ignore: [main]

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-and-push.yml
    with:
      IMAGE_TAG: $GITHUB_REF_NAME
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
