name: Main branch workflow

on:
  push:
    branches: main

env:
  IMAGE_NAME: samanthamorris684/catbot

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-and-push.yml
    with:
      IMAGE_TAG: $GITHUB_SHA
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-eks:
    uses: ./.github/workflows/deploy-to-eks.yml
    with:
      IMAGE_TAG: $GITHUB_SHA
      