name: Main branch workflow

on:
  push:
    branches: main

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-and-push.yml
    with:
      IMAGE_TAG: ${{ github.sha }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-eks:
    needs: build-and-push-image
    uses: ./.github/workflows/deploy-to-eks.yml
    permissions:
      id-token: write
      contents: read
    with:
      IMAGE_TAG: ${{ github.sha }}
    secrets:
      GH_ACTIONS_ROLE: ${{ secrets.GH_ACTIONS_ROLE }}
      