name: Main branch workflow

on:
  release:
    types: [published]

env:
  IMAGE_NAME: samanthamorris684/catbot

jobs:
  build-and-push-main:
    uses: ./.github/workflows/build-and-push.yml
    with:
      IMAGE_TAG: $GITHUB_SHA
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 
  update-cluster:
    name: Update with new image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new docker image to cluster
        uses: tuongaz/kubectl-eks-action@1.0.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_BASE_64_ENCODED }}
        with:
          args: set image deployment/server-deployment container-name=$IMAGE_NAME:$GITHUB_SHA
