name: Pull request workflow

on:
  pull_request

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-and-push.yml
    with:
      IMAGE_TAG: pr-${{ github.event.number }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
        TC_CLOUD_TOKEN: ${{ secrets.TC_CLOUD_TOKEN }}
  scout:
    permissions:
      pull-requests: write
    needs: build-and-push-image
    uses: ./.github/workflows/scout.yml
    with:
      IMAGE_TAG: pr-${{ github.event.number }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
