name: Security workflow
on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string

env:
  REGISTRY: samanthamorris684
  IMAGE_NAME: catbot
  COMPARE_TAG: latest
  USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: compare
          image: $IMAGE_NAME:${{ inputs.IMAGE_TAG }}
          to: ${{ env.IMAGE_NAME }}:${{ env.COMPARE_TAG }}
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }} # to be able to write the comment